{
 "title": "JMX for fink-broker",
 "tags": [ "kubernetes-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\", cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(kube_pod_info{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Used buffers of a given JVM buffer pool (direct)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(jvm_buffer_pool_used_buffers{namespace=\"$namespace\", pool=\"direct\", job=\"spark/fink-broker\", container!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used buffers of a given JVM buffer pool (mapped)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "sum(jvm_buffer_pool_used_buffers{namespace=\"$namespace\", pool=\"mapped\", job=\"spark/fink-broker\", container!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes capacity of a given JVM buffer pool (direct)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(jvm_buffer_pool_capacity_bytes{namespace=\"$namespace\", pool=\"direct\", job=\"spark/fink-broker\", container!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes capacity of a given JVM buffer pool(mapped)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 10 },
   "targets": [
    {
     "expr": "sum(jvm_buffer_pool_capacity_bytes{namespace=\"$namespace\", pool=\"mapped\", job=\"spark/fink-broker\", container!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}