{{- define "fink.stream2raw.spec" -}}
{{- include "fink.common" . }}
mainApplicationFile: local:///home/fink/fink-broker/bin/ztf/stream2raw.py
arguments: {{- include "fink.commonargs" . | nindent 2 }}
  - '-servers'
  - '{{ .Values.stream2raw.kafka.in_sockets }}'
  - '-schema'
  - '{{ .Values.stream2raw.fink_alert_schema }}'
  - '-startingoffsets_stream'
  - '{{ .Values.stream2raw.kafka.starting_offset }}'
  - '-topic'
  - '{{ .Values.stream2raw.kafka.topic }}'
  {{- include "fink.nightargs" . | nindent 2 }}
sparkVersion: "3.4.1"
sparkConf: {{- include "fink.s3config" . | nindent 2 }}
driver:
  cores: {{ tpl .Values.stream2raw.cores . }}
  coreRequest: "{{ tpl .Values.stream2raw.coreRequest . }}"
  env: {{- include "fink.hdfsconfig" . | nindent 4 }}
  memory: "{{ tpl .Values.stream2raw.memory . }}"
  labels:
    version: 3.4.1
  serviceAccount: spark
  javaOptions: "-Divy.cache.dir=/tmp -Divy.home=/tmp -Dcom.amazonaws.sdk.disableCertChecking=true"
executor:
  cores: {{ tpl .Values.stream2raw.cores . }}
  coreRequest: "{{ tpl .Values.stream2raw.coreRequest . }}"
  env: {{- include "fink.hdfsconfig" . | nindent 4 }}
  memory: "{{ tpl .Values.stream2raw.memory . }}"
  instances: {{ tpl .Values.stream2raw.instances . }}
  javaOptions: "-Dcom.amazonaws.sdk.disableCertChecking=true"
  labels:
    version: 3.4.1
{{- if eq .Values.monitoring.enabled true }}
monitoring:
  exposeDriverMetrics: true
  exposeExecutorMetrics: true
  prometheus:
    # Added in Dockerfile
    jmxExporterJar: "/opt/spark/jars/jmx_prometheus_javaagent-1.1.0.jar"
    port: 8090
{{- end }}
{{- end }}
{{- include "fink.sparkapp" (dict "ctx" . "name" "stream2raw" "spec" "fink.stream2raw.spec") }}
