{
 "title": "JMX for fink-broker",
 "tags": [ "kubernetes-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\", cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(kube_pod_info{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of open file descriptors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(process_open_fds{namespace=\"$namespace\", job=\"spark/fink-broker\", container!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maximum number of open file descriptors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(process_max_fds{namespace=\"$namespace\", job=\"spark/fink-broker\", container!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "TODO user rat() Total user and system CPU time spent in seconds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(process_cpu_seconds_total{namespace=\"$namespace\", job=\"spark/fink-broker\", container!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true
  },
  {
   "title": "Committed (bytes) of a given JVM memory area",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(jvm_memory_committed_bytes{namespace=\"$namespace\", job=\"spark/fink-broker\", container!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Virtual memory size in bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(process_virtual_memory_bytes{namespace=\"$namespace\", job=\"spark/fink-broker\", container!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max (bytes) of a given JVM memory area",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(jvm_memory_max_bytes{namespace=\"$namespace\", job=\"spark/fink-broker\", container!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total bytes allocated in a given JVM memory pool. Only updated after GC, not continuously.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "sum(jvm_memory_pool_allocated_bytes_total{namespace=\"$namespace\", job=\"spark/fink-broker\", container!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Committed bytes of a given JVM memory pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum(jvm_memory_pool_committed_bytes{namespace=\"$namespace\", job=\"spark/fink-broker\", container!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max bytes of a given JVM memory pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "sum(jvm_memory_pool_max_bytes{namespace=\"$namespace\", job=\"spark/fink-broker\", container!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used bytes of a given JVM memory pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum(jvm_memory_pool_used_bytes{namespace=\"$namespace\", job=\"spark/fink-broker\", container!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used bytes of a given JVM memory area",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=\"$namespace\", job=\"spark/fink-broker\", container!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Garbage collector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true
  },
  {
   "title": "Time spent in JVM garbage collector in seconds.",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "sum(jvm_gc_collection_seconds_sum{namespace=\"$namespace\", job=\"spark/fink-broker\", container!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "JVM buffer pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Used buffers (direct)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "sum(jvm_buffer_pool_used_buffers{namespace=\"$namespace\", pool=\"direct\", job=\"spark/fink-broker\", container!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used buffers (mapped)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 64 },
   "targets": [
    {
     "expr": "sum(jvm_buffer_pool_used_buffers{namespace=\"$namespace\", pool=\"mapped\", job=\"spark/fink-broker\", container!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes capacity (direct)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "sum(jvm_buffer_pool_capacity_bytes{namespace=\"$namespace\", pool=\"direct\", job=\"spark/fink-broker\", container!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes capacity (mapped)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 74 },
   "targets": [
    {
     "expr": "sum(jvm_buffer_pool_capacity_bytes{namespace=\"$namespace\", pool=\"mapped\", job=\"spark/fink-broker\", container!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of classes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "collapsed": true
  },
  {
   "title": "Currently loaded in the JVM",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "sum(jvm_classes_currently_loaded{namespace=\"$namespace\", job=\"spark/fink-broker\", container!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loaded since the JVM has started",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 85 },
   "targets": [
    {
     "expr": "sum(jvm_classes_loaded_total{namespace=\"$namespace\", job=\"spark/fink-broker\", container!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}