{
 "title": "JMX for fink-broker",
 "tags": [ "kubernetes-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\", cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(kube_pod_info{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of open file descriptors",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum(process_open_fds{namespace=\"$namespace\", job=\"spark/fink-broker\", container!=\"\"}) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Maximum number of open file descriptors",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "sum(process_max_fds{namespace=\"$namespace\", job=\"spark/fink-broker\", container!=\"\"}) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Rate on 5m for total user and system CPU time spent in seconds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(process_cpu_seconds_total{namespace=\"$namespace\", job=\"spark/fink-broker\", container!=\"\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true
  },
  {
   "title": "Committed (MB) of a given JVM memory area",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(jvm_memory_committed_bytes{namespace=\"$namespace\", job=\"spark/fink-broker\", container!=\"\"}) by (pod) / 1000 / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Virtual memory size (MB)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(process_virtual_memory_bytes{namespace=\"$namespace\", job=\"spark/fink-broker\", container!=\"\"}) by (pod) / 1000 / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max (bytes) of a given JVM memory area",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(jvm_memory_max_bytes{namespace=\"$namespace\", job=\"spark/fink-broker\", container!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total memory allocated in a given JVM memory pool. Only updated after GC, not continuously (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "sum(jvm_memory_pool_allocated_bytes_total{namespace=\"$namespace\", job=\"spark/fink-broker\", container!=\"\"}) by (pod) / 1000 / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Committed memory of a given JVM memory pool (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum(jvm_memory_pool_committed_bytes{namespace=\"$namespace\", job=\"spark/fink-broker\", container!=\"\"}) by (pod) / 1000 / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max memory of a given JVM memory pool (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "sum(jvm_memory_pool_max_bytes{namespace=\"$namespace\", job=\"spark/fink-broker\", container!=\"\"}) by (pod) / 1000 / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used bytes of a given JVM memory pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum(jvm_memory_pool_used_bytes{namespace=\"$namespace\", job=\"spark/fink-broker\", container!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used bytes of a given JVM memory area",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=\"$namespace\", job=\"spark/fink-broker\", container!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Garbage collector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true
  },
  {
   "title": "Time spent in JVM garbage collector in seconds.",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum(jvm_gc_collection_seconds_sum{namespace=\"$namespace\", job=\"spark/fink-broker\", container!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "JVM buffer pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Used buffers (direct)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum(jvm_buffer_pool_used_buffers{namespace=\"$namespace\", pool=\"direct\", job=\"spark/fink-broker\", container!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used buffers (mapped)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 52 },
   "targets": [
    {
     "expr": "sum(jvm_buffer_pool_used_buffers{namespace=\"$namespace\", pool=\"mapped\", job=\"spark/fink-broker\", container!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes capacity (direct)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "sum(jvm_buffer_pool_capacity_bytes{namespace=\"$namespace\", pool=\"direct\", job=\"spark/fink-broker\", container!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes capacity (mapped)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 62 },
   "targets": [
    {
     "expr": "sum(jvm_buffer_pool_capacity_bytes{namespace=\"$namespace\", pool=\"mapped\", job=\"spark/fink-broker\", container!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of classes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true
  },
  {
   "title": "Currently loaded in the JVM",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "sum(jvm_classes_currently_loaded{namespace=\"$namespace\", job=\"spark/fink-broker\", container!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loaded since the JVM has started",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 73 },
   "targets": [
    {
     "expr": "sum(jvm_classes_loaded_total{namespace=\"$namespace\", job=\"spark/fink-broker\", container!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}