= Developer guide for Kubernetes users

== Managing fink-broker images

`Fink-broker` container images for Kubernetes are based on https://github.com/astrolabsoftware/k8s-spark-py.git[k8s-spark-py] images.

=== Pre-requisites

Clone the project:

[,shell]
----
git clone https://github.com/astrolabsoftware/fink-broker.git
cd fink-broker
----

`conf.sh` contains all build parameters with inline documenation for all of them. For example, edit `SPARK_IMAGE_TAG` value in `conf.sh` in order to customize the base image used to `fink-broker` container image.

=== Build the image:

[,shell]
----
./build.sh
----


=== Push the image to CC-IN2P3 registry

This is usefull to share image among multiples users or infrastructures.

[,shell]
----
# Log in IN2P3 registry
docker login gitlab-registry.in2p3.fr
./push-image.sh
----

== Run integration tests

It is possible to run integration tests locally. The `itest` section of `.github/workflows/ci.yml` display the shell commands required to perform these task. It is possible to launch these commands locally or against a Kubernetes cluster.

== Automated build

The CI will automatically build, run integration tests and eventually push `fink-broker` container image inside IN2P3 registry for each commit to the git repository.