name: "e2e: science, self-hosted"
on:
  schedule:
    # At 05:00 UTC on every day-of-week from Monday through Friday.
    - cron:  '0 5 * * 1-5'
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/e2e.yml
    with:
      noscience: false
    secrets:
      registry_username: ${{ secrets.REGISTRY_USERNAME }}
      registry_token: ${{ secrets.REGISTRY_TOKEN }}
