name: "e2e: platform=sentinel, survey=rubin, science=true, infra=github"

on:
  workflow_dispatch:

jobs:
  call-sentinel-template:
    uses: ./.github/workflows/sentinel-template.yml
    with:
      survey: rubin