name: "e2e: platform=sentinel, survey=rubin, science=true, infra=github"

on:
  push:
  pull_request:
    branches:
      - master
  schedule:
    # At 03:00 UTC on Sunday
    - cron: '0 3 * * 0'
  workflow_dispatch:

jobs:
  call-sentinel-template:
    uses: ./.github/workflows/sentinel-template.yml
    with:
      survey: rubin
      # Last fink-deps-sentinel image known to pass, still on Python 3.11
      image_tag: 'v2.54.10-rc8-17-g34a543b'
