name: "Fink-broker e2e workflow (noscience, self-hosted)"
on:
  schedule:
    # At 03:00 UTC on every day-of-week from Monday through Friday.
    - cron:  '0 3 * * 1-5'

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/itest.yml
    with:
      minimal: true
      noscience: true
    secrets:
      registry_username: ${{ secrets.REGISTRY_USERNAME }}
      registry_token: ${{ secrets.REGISTRY_TOKEN }}
