name: SonarQube

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.organization=astrolabsoftware
          -Dsonar.projectKey=finkbroker
          -Dsonar.sources=fink_broker/,bin/
          -Dsonar.test.exclusions=fink_broker/htmlcov,fink_broker/slackUtils.py
          -Dsonar.verbose=true
          -Dsonar.coverage.exclusions=**/**
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
