name: Centos

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  basic:
    runs-on: ubuntu-latest
    container:
      image: quay.io/centos/centos:stream9
    strategy:
      matrix:
        python-version: [3.7]
        spark-version: [3.1.3]
    steps:
    - uses: actions/checkout@v2
    - name: Install add-ons
      run: |
        dnf install -y wget java-11-openjdk
    - name: Check Java installation
      run: java -version
    - name: What OS is running
      run: cat /etc/centos-release
